#  Copyright (C) 2018-2022 LEIDOS.
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# Configuration file for Sonar Scanner used for CI 

sonar.projectKey=usdot-fhwa-stol_autoware-auto
sonar.organization=usdot-fhwa-stol
sonar.cfamily.cache.enabled=false
sonar.cfamily.compile-commands=/opt/carma/build/compile_commands.json
sonar.cfamily.gcov.reportsPath=/opt/carma/coverage_reports/gcov
sonar.coverageReportPaths=/opt/carma/coverage_reports/gcov/coverage.xml
sonar.projectName=autoware.auto
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io
# Set Git as SCM sensor
sonar.scm.disabled=false
sonar.scm.enabled=true
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=.cpp,.h,.tpp

# Modules

sonar.modules=autoware_auto_tf2, \
controller_common, \
pure_pursuit, \
trajectory_follower, \
trajectory_follower_nodes, \
tracking, \
tracking_nodes

autoware_auto_tf2.sonar.projectBaseDir   =/opt/carma/src/autoware.auto/AutowareAuto/src/common/autoware_auto_tf2
controller_common.sonar.projectBaseDir   =/opt/carma/src/autoware.auto/AutowareAuto/src/control/controller_common
pure_pursuit.sonar.projectBaseDir   =/opt/carma/src/autoware.auto/AutowareAuto/src/control/pure_pursuit
trajectory_follower.sonar.projectBaseDir   =/opt/carma/src/autoware.auto/AutowareAuto/src/control/trajectory_follower
trajectory_follower_nodes.sonar.projectBaseDir   =/opt/carma/src/autoware.auto/AutowareAuto/src/control/trajectory_follower_nodes
tracking.sonar.projectBaseDir   =/opt/carma/src/autoware.auto/AutowareAuto/src/perception/tracking
tracking_nodes.sonar.projectBaseDir   =/opt/carma/src/autoware.auto/AutowareAuto/src/perception/tracking_nodes


# Tests

autoware_auto_tf2.sonar.tests                 = /opt/carma/src/autoware.auto/AutowareAuto/src/common/autoware_auto_tf2/test
controller_common.sonar.tests        = /opt/carma/src/autoware.auto/AutowareAuto/src/control/controller_common/test
pure_pursuit.sonar.tests                       =/opt/carma/src/autoware.auto/AutowareAuto/src/control/pure_pursuit/test
trajectory_follower.sonar.tests            = /opt/carma/src/autoware.auto/AutowareAuto/src/control/trajectory_follower/test
trajectory_follower_nodes.sonar.tests                      = /opt/carma/src/autoware.auto/AutowareAuto/src/control/trajectory_follower_nodes/test
tracking.sonar.tests                      = /opt/carma/src/autoware.auto/AutowareAuto/src/perception/tracking/test
tracking_nodes.sonar.tests                    = /opt/carma/src/autoware.auto/AutowareAuto/src/perception/tracking_nodes/test
